# -----------------------------
# FFHQ_Ref training config for VOSR-0.5B multi-step
# short-run sanity check version
# -----------------------------

train_dataset_config: null
suffix: '_ffhq_ref_debug'

# FFHQ_Ref test setting
test_lq_dir: null
test_gt_dir: null 
test_upscale: 1

ffhq_ref_test_use_csv_for_eval: True
ffhq_ref_eval_hq_dir: /data/zhangdanning/Projects/ref-ldm/data/FFHQ-Ref/images1024x1024
ffhq_ref_eval_lq_dir: /data/zhangdanning/Projects/ref-ldm/data/FFHQ-Ref/test_images/moderate_degrad

infer_steps: 25
resolution: 512
train_batch_size: 2
gradient_accumulation_steps: 1
dataloader_num_workers: 2 # previous:8 [change]

# Model configuration
patch_size: 2
mlp_ratio: 4
use_qknorm: True
use_swiglu: True
use_rope: True
use_rmsnorm: True
wo_shift: False

dim: 1024
depth: 28
num_heads: 16

use_8bit_adam: False

# AE
ae_type: sd2
ae_path: preset/ckpts/stable-diffusion-2-1-base
lwdecoder_path: preset/ckpts/sd21_lwdecoder.pth

# Training configuration
learning_rate: 5.0e-5
max_train_steps: 200 # previous:400001 [change]
checkpointing_steps: 50 # previous:10000 [change]
inference_steps: 50 # previous:10000 [change]
adam_beta1: 0.9
adam_beta2: 0.95
adam_weight_decay: 1.0e-2
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
lr_scheduler: constant_with_warmup
lr_warmup_steps: 50 # previous:0 [change]
lr_num_cycles: 1
use_ema: True
mixed_precision: 'no'
tracker_project_name: vosr
seed: 42
ema_decay: 0.9999

time_dist: ['uniform', 0, 1.0]

cfg_ratio: 0.1
cfg_scale: -0.5

weak_cond_strength_aelq_list: [0.05, 0.25]
cond_strength_aelq_list: [5, 1]

dinov2_size: 448
enc_type: dinov2b
enc_dim: 768
layer_dinov2b_list: [8]

interp_type: lin

a: 1.0
b: 1.0

use_pos: False
train_steps: 2
encdim_ratio: 3
t_start: 0
t_end: 1
resume_ckpt: ~
pretrained_ckpt: preset/ckpts/VOSR_0.5B_ms/checkpoints/ema_model.safetensors

# logging
logging_dir: logs
output_dir: exp_vosr_test/
report_to: none

#dinov2
dinov2_local_repo: /data/zhangdanning/Projects/VOSR/preset/dinov2

# dataset
dataset_type: 'ffhq_ref'

# FFHQ_Ref paths
ffhq_ref_hq_dir: /data/zhangdanning/Projects/ref-ldm/data/FFHQ-Ref/images1024x1024
ffhq_ref_lq_dir: null

ffhq_ref_train_csv: /data/zhangdanning/Projects/ref-ldm/data/FFHQ-Ref/reference_mapping/train_references_small20.csv
ffhq_ref_val_csv: /data/zhangdanning/Projects/ref-ldm/data/FFHQ-Ref/reference_mapping/val_references_small10.csv
ffhq_ref_test_csv: /data/zhangdanning/Projects/ref-ldm/data/FFHQ-Ref/reference_mapping/test_references_small10.csv

ffhq_ref_num_refs: 5
ffhq_ref_return_ref: False
ffhq_ref_crop_mode: random